#!/usr/bin/ruby

# encoding: UTF-8

require_relative "src/Ruby/loader.rb"

# -------------------------------------------------------------------------

class ProgramVariant
    # ProgramVariant::id()
    def self.id()
        "docnet"
    end
end

EstateServices::ensureReadiness()
DataPortalUI::dataPortalFront()

# -------------------------------------------------------------------------
