#!/usr/bin/ruby

# encoding: UTF-8

require_relative "Libs/loader.rb"

# ----------------------------------------------------------------------------

if ARGV[0] == "make" and ARGV[1] == "datacarrier" then
    object = DataCarriers::interactivelyIssueNewDataCarrierOrNull()
    puts JSON.pretty_generate(object)
    exit
end

puts "usage:"
puts "    docnet make datacarrier"
